/*
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright(c) 2024 Napatech A/S
 */

#ifndef _NTHW_FPGA_REG_DEFS_MAC_TX_
#define _NTHW_FPGA_REG_DEFS_MAC_TX_

/* MAC_TX */
#define MAC_TX_PACKET_SMALL (0xcfcb5e97UL)
#define MAC_TX_PACKET_SMALL_COUNT (0x84345b01UL)
#define MAC_TX_TOTAL_BYTES (0x7bd15854UL)
#define MAC_TX_TOTAL_BYTES_COUNT (0x61fb238cUL)
#define MAC_TX_TOTAL_GOOD_BYTES (0xcf0260fUL)
#define MAC_TX_TOTAL_GOOD_BYTES_COUNT (0x8603398UL)
#define MAC_TX_TOTAL_GOOD_PACKETS (0xd89f151UL)
#define MAC_TX_TOTAL_GOOD_PACKETS_COUNT (0x12c47c77UL)
#define MAC_TX_TOTAL_PACKETS (0xe37b5ed4UL)
#define MAC_TX_TOTAL_PACKETS_COUNT (0x21ddd2ddUL)

#endif	/* _NTHW_FPGA_REG_DEFS_MAC_TX_ */
