# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2016 Neil Horman <nhorman@tuxdriver.com>
# All rights reserved.

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-y += pmdinfogen

include $(RTE_SDK)/mk/rte.subdir.mk
