# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2018 Luca Boccassi <bluca@debian.org>

ccflags-y := $(MODULE_CFLAGS)
obj-m := rte_kni.o
rte_kni-y := $(patsubst $(src)/%.c,%.o,$(wildcard $(src)/*.c))
