/*-
 * F-Stack M5: 14.0+ kernel symbol stubs for example/ link.
 *
 * These are user-space stubs for kernel symbols introduced in FreeBSD 14.0+
 * (rib new API, netlink/genl, tcp ECN/HPTS, aio, nvlist, m_snd_tag, tqhash,
 *  prison_check_ip*_locked, vm pages, etc.) referenced by libfstack.ro at link
 * time but not exercised by F-Stack default user-space code paths.
 *
 * Strategy: provide minimal-link-only stubs (no-op functions / zero data) so
 * example/ binaries can link. Runtime invocation of any unimplemented stub
 * indicates code path not supported by user-space F-Stack lib.
 *
 * Auto-generated by /tmp/m5_gen_stub.py — do not hand-edit per-symbol bodies;
 * extend STUBS dict and regenerate instead.
 */

#include <sys/cdefs.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/kernel.h>
#include <sys/systm.h>
#include <sys/errno.h>
#include <sys/lock.h>
#include <sys/mutex.h>
#include <sys/proc.h>
#include <sys/socket.h>
#include <sys/file.h>
#include <sys/malloc.h>
#include <sys/uio.h>
#include <sys/jail.h>
#include <netinet/in.h>
#include <vm/vm.h>
#include <vm/vm_param.h>
#include <vm/vm_page.h>
#include <machine/pmap.h>

/* Forward decls for opaque kernel types not pulled by includes above. */
struct kaiocb;
typedef int (aio_cancel_fn_t)(struct kaiocb *);
struct buf_ring;
struct nlattr;
struct nl_pstate;
struct nl_writer;
struct nlmsghdr;
struct nlpcb;
struct nlattr_bmask;
struct rib_head;
struct rib_subscription;
struct rtentry;
struct route_nhop_data;
struct nhop_object;
struct rtbridge;
struct tcpcb;
struct syncache;
struct m_snd_tag;
struct if_snd_tag_sw;
union if_snd_tag_alloc_params;
struct sendfile_sync;
struct vmspace;
struct ksiginfo;
typedef struct ksiginfo ksiginfo_t;
struct nvlist;
typedef struct nvlist nvlist_t;
struct bitset;
typedef struct ifnet *if_t;

/* ===== Stubs (auto-generated) ===== */

int aio_cancel_cleared(struct kaiocb *job);
int aio_cancel_cleared(struct kaiocb *job)
{
    return (0);
}

void aio_clear_cancel_function(struct kaiocb *job);
void aio_clear_cancel_function(struct kaiocb *job)
{
    
}

void aio_complete(struct kaiocb *job, long status, int error);
void aio_complete(struct kaiocb *job, long status, int error)
{
    
}

int aio_set_cancel_function(struct kaiocb *job, aio_cancel_fn_t *func);
int aio_set_cancel_function(struct kaiocb *job, aio_cancel_fn_t *func)
{
    return (0);
}

void aio_switch_vmspace(struct kaiocb *job);
void aio_switch_vmspace(struct kaiocb *job)
{
    
}

void ast_register(int ast, int t, int f, void (*hdlr)(struct thread *, int));
void ast_register(int ast, int t, int f, void (*hdlr)(struct thread *, int))
{
    
}

const struct fileops badfileops = {0};

int boottrace(const char *tdname, const char *eventfmt, ...);
int boottrace(const char *tdname, const char *eventfmt, ...)
{
    return (0);
}

bool boottrace_enabled = false;

struct buf_ring *buf_ring_alloc(int count, struct malloc_type *type, int flags, struct mtx *lock);
struct buf_ring *buf_ring_alloc(int count, struct malloc_type *type, int flags, struct mtx *lock)
{
    return (NULL);
}

void buf_ring_free(struct buf_ring *br, struct malloc_type *type);
void buf_ring_free(struct buf_ring *br, struct malloc_type *type)
{
    
}

void callout_when(sbintime_t sbt, sbintime_t precision, int flags, sbintime_t *sbt_out, sbintime_t *precision_out);
void callout_when(sbintime_t sbt, sbintime_t precision, int flags, sbintime_t *sbt_out, sbintime_t *precision_out)
{
    
}

vm_paddr_t dump_avail[16] = {0};

void fdescfree_adapt_use(struct proc *p);
void fdescfree_adapt_use(struct proc *p)
{
    
}

void freeuio(struct uio *uio);
void freeuio(struct uio *uio)
{
    if (uio) free(uio, M_IOV);
}

bool genl_register_cmds(uint16_t family, const void *cmds, int count);
bool genl_register_cmds(uint16_t family, const void *cmds, int count)
{
    return (false);
}

uint16_t genl_register_family(const char *family_name, size_t hdrsize, int family_version, int max_attr_idx);
uint16_t genl_register_family(const char *family_name, size_t hdrsize, int family_version, int max_attr_idx)
{
    return (0);
}

void genl_unregister_family(uint16_t family);
void genl_unregister_family(uint16_t family)
{
    
}

void _gone_in(int major, const char *msg, ...);
void _gone_in(int major, const char *msg, ...)
{
    
}

volatile uint32_t hpts_that_need_softclock = 0;

int inotify_create_file(struct thread *td, struct file *fp, int flags, int *fflagsp);
int inotify_create_file(struct thread *td, struct file *fp, int flags, int *fflagsp)
{
    return (ENOSYS);
}

int invfo_chmod(struct file *fp, mode_t mode, struct ucred *active_cred, struct thread *td);
int invfo_chmod(struct file *fp, mode_t mode, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

int invfo_chown(struct file *fp, uid_t uid, gid_t gid, struct ucred *active_cred, struct thread *td);
int invfo_chown(struct file *fp, uid_t uid, gid_t gid, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

int invfo_rdwr(struct file *fp, struct uio *uio, struct ucred *active_cred, int flags, struct thread *td);
int invfo_rdwr(struct file *fp, struct uio *uio, struct ucred *active_cred, int flags, struct thread *td)
{
    return (EOPNOTSUPP);
}

int invfo_sendfile(struct file *fp, int sockfd, struct uio *hdr_uio, struct uio *trl_uio, off_t offset, size_t nbytes, off_t *sent, int flags, struct thread *td);
int invfo_sendfile(struct file *fp, int sockfd, struct uio *hdr_uio, struct uio *trl_uio, off_t offset, size_t nbytes, off_t *sent, int flags, struct thread *td)
{
    return (EOPNOTSUPP);
}

int invfo_truncate(struct file *fp, off_t length, struct ucred *active_cred, struct thread *td);
int invfo_truncate(struct file *fp, off_t length, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

bool is_random_seeded(void);
bool is_random_seeded(void)
{
    return (true);
}

void kern_psignal(struct proc *p, int sig);
void kern_psignal(struct proc *p, int sig)
{
    
}

int kproc_create(void (*fn)(void *), void *arg, struct proc **pp, int flags, int pages, const char *fmt, ...);
int kproc_create(void (*fn)(void *), void *arg, struct proc **pp, int flags, int pages, const char *fmt, ...)
{
    return (0);
}

void ktrexterr(struct thread *td);
void ktrexterr(struct thread *td)
{
    
}

struct kva_layout_s kva_layout = {0};

MALLOC_DEFINE(M_NVLIST, "nvlist", "kernel nvlist");

void m_rcvif_restore(struct mbuf *m, if_t ifp, void *cookie);
void m_rcvif_restore(struct mbuf *m, if_t ifp, void *cookie)
{
    
}

void *m_rcvif_serialize(struct mbuf *m);
void *m_rcvif_serialize(struct mbuf *m)
{
    return (NULL);
}

int m_snd_tag_alloc(if_t ifp, union if_snd_tag_alloc_params *params, struct m_snd_tag **mstp);
int m_snd_tag_alloc(if_t ifp, union if_snd_tag_alloc_params *params, struct m_snd_tag **mstp)
{
    return (EOPNOTSUPP);
}

void m_snd_tag_destroy(struct m_snd_tag *mst);
void m_snd_tag_destroy(struct m_snd_tag *mst)
{
    
}

void m_snd_tag_init(struct m_snd_tag *mst, if_t ifp, const struct if_snd_tag_sw *sw);
void m_snd_tag_init(struct m_snd_tag *mst, if_t ifp, const struct if_snd_tag_sw *sw)
{
    
}

void mtx_wait_unlocked(struct mtx *m);
void mtx_wait_unlocked(struct mtx *m)
{
    
}

struct rtbridge *netlink_callback_p = NULL;

bool nlattr_add(struct nl_writer *nw, uint16_t attr_type, uint16_t attr_len, const void *data);
bool nlattr_add(struct nl_writer *nw, uint16_t attr_type, uint16_t attr_len, const void *data)
{
    return (false);
}

int nlattr_get_in6_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_in6_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_in_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_in_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_nla(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_nla(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_string(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_string(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint16(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint16(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint32(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint32(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint8(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint8(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_save_offset(struct nl_writer *nw);
int nlattr_save_offset(struct nl_writer *nw)
{
    return (0);
}

int nl_modify_ifp_generic(if_t ifp, struct nlattr_bmask *bm, struct nl_pstate *npt);
int nl_modify_ifp_generic(if_t ifp, struct nlattr_bmask *bm, struct nl_pstate *npt)
{
    return (EOPNOTSUPP);
}

void nlmsg_abort(struct nl_writer *nw);
void nlmsg_abort(struct nl_writer *nw)
{
    
}

bool nlmsg_add(struct nl_writer *nw, uint32_t portid, uint32_t seq, uint16_t type, uint16_t flags, uint32_t len);
bool nlmsg_add(struct nl_writer *nw, uint32_t portid, uint32_t seq, uint16_t type, uint16_t flags, uint32_t len)
{
    return (false);
}

bool nlmsg_end(struct nl_writer *nw);
bool nlmsg_end(struct nl_writer *nw)
{
    return (false);
}

bool nlmsg_end_dump(struct nl_writer *nw, int error, struct nlmsghdr *hdr);
bool nlmsg_end_dump(struct nl_writer *nw, int error, struct nlmsghdr *hdr)
{
    return (false);
}

void nlmsg_report_err_msg(struct nl_pstate *npt, const char *fmt, ...);
void nlmsg_report_err_msg(struct nl_pstate *npt, const char *fmt, ...)
{
    
}

void *nlmsg_reserve_data_raw(struct nl_writer *nw, size_t sz);
void *nlmsg_reserve_data_raw(struct nl_writer *nw, size_t sz)
{
    return (NULL);
}

int nl_parse_attrs_raw(struct nlattr *nla_head, int len, const void *parser, struct nl_pstate *npt, void *target);
int nl_parse_attrs_raw(struct nlattr *nla_head, int len, const void *parser, struct nl_pstate *npt, void *target)
{
    return (EINVAL);
}

struct ucred *nlp_get_cred(struct nlpcb *nlp);
struct ucred *nlp_get_cred(struct nlpcb *nlp)
{
    return (NULL);
}

void nvlist_add_bool(nvlist_t *nvl, const char *name, bool value);
void nvlist_add_bool(nvlist_t *nvl, const char *name, bool value)
{
    
}

nvlist_t *nvlist_create(int flags);
nvlist_t *nvlist_create(int flags)
{
    return (NULL);
}

void nvlist_destroy(nvlist_t *nvl);
void nvlist_destroy(nvlist_t *nvl)
{
    
}

int nvlist_error(const nvlist_t *nvl);
int nvlist_error(const nvlist_t *nvl)
{
    return (0);
}

bool nvlist_exists_bool(const nvlist_t *nvl, const char *name);
bool nvlist_exists_bool(const nvlist_t *nvl, const char *name)
{
    return (false);
}

bool nvlist_get_bool(const nvlist_t *nvl, const char *name);
bool nvlist_get_bool(const nvlist_t *nvl, const char *name)
{
    return (false);
}

void *nvlist_pack(const nvlist_t *nvl, size_t *sizep);
void *nvlist_pack(const nvlist_t *nvl, size_t *sizep)
{
    return (NULL);
}

nvlist_t *nvlist_unpack(const void *buf, size_t size, int flags);
nvlist_t *nvlist_unpack(const void *buf, size_t size, int flags)
{
    return (NULL);
}

const struct fileops path_fileops = {0};

vm_page_t PHYS_TO_VM_PAGE(vm_paddr_t pa);
vm_page_t PHYS_TO_VM_PAGE(vm_paddr_t pa)
{
    return (NULL);
}

int prison_check_ip4_locked(const struct prison *pr, const struct in_addr *ia);
int prison_check_ip4_locked(const struct prison *pr, const struct in_addr *ia)
{
    return (0);
}

int prison_check_ip6_locked(const struct prison *pr, const struct in6_addr *ia6);
int prison_check_ip6_locked(const struct prison *pr, const struct in6_addr *ia6)
{
    return (0);
}

bool prison_isalive(const struct prison *pr);
bool prison_isalive(const struct prison *pr)
{
    return (true);
}

void rack_update_pcm_ack(void *rack, int was_pcm, uint32_t ack, uint32_t to);
void rack_update_pcm_ack(void *rack, int was_pcm, uint32_t ack, uint32_t to)
{
    
}

void rib_destroy_subscriptions(struct rib_head *rnh);
void rib_destroy_subscriptions(struct rib_head *rnh)
{
    
}

void rib_init_subscriptions(struct rib_head *rnh);
void rib_init_subscriptions(struct rib_head *rnh)
{
    
}

void rib_notify(struct rib_head *rnh, int type, void *data);
void rib_notify(struct rib_head *rnh, int type, void *data)
{
    
}

struct rib_subscription *rib_subscribe_internal(struct rib_head *rnh, void (*cb)(struct rib_head *, void *, void *), void *arg, int type, bool waitok);
struct rib_subscription *rib_subscribe_internal(struct rib_head *rnh, void (*cb)(struct rib_head *, void *, void *), void *arg, int type, bool waitok)
{
    return (NULL);
}

struct rtentry *rt_alloc(struct rib_head *rnh, const struct sockaddr *dst, struct route_nhop_data *rnd);
struct rtentry *rt_alloc(struct rib_head *rnh, const struct sockaddr *dst, struct route_nhop_data *rnd)
{
    return (NULL);
}

void rt_free(struct rtentry *rt);
void rt_free(struct rtentry *rt)
{
    
}

void rt_free_immediate(struct rtentry *rt);
void rt_free_immediate(struct rtentry *rt)
{
    
}

int rt_get_family(const struct rtentry *rt);
int rt_get_family(const struct rtentry *rt)
{
    return (AF_UNSPEC);
}

void rt_get_inet6_prefix_plen(const struct rtentry *rt, struct in6_addr *paddr, int *plen, uint32_t *pscopeid);
void rt_get_inet6_prefix_plen(const struct rtentry *rt, struct in6_addr *paddr, int *plen, uint32_t *pscopeid)
{
    
}

void rt_get_inet6_prefix_pmask(const struct rtentry *rt, struct in6_addr *paddr, struct in6_addr *pmask, uint32_t *pscopeid);
void rt_get_inet6_prefix_pmask(const struct rtentry *rt, struct in6_addr *paddr, struct in6_addr *pmask, uint32_t *pscopeid)
{
    
}

void rt_get_inet_prefix_plen(const struct rtentry *rt, struct in_addr *paddr, int *plen, uint32_t *pscopeid);
void rt_get_inet_prefix_plen(const struct rtentry *rt, struct in_addr *paddr, int *plen, uint32_t *pscopeid)
{
    
}

void rt_get_inet_prefix_pmask(const struct rtentry *rt, struct in_addr *paddr, struct in_addr *pmask, uint32_t *pscopeid);
void rt_get_inet_prefix_pmask(const struct rtentry *rt, struct in_addr *paddr, struct in_addr *pmask, uint32_t *pscopeid)
{
    
}

struct nhop_object *rt_get_raw_nhop(const struct rtentry *rt);
struct nhop_object *rt_get_raw_nhop(const struct rtentry *rt)
{
    return (NULL);
}

bool rt_is_exportable(const struct rtentry *rt, struct ucred *cr);
bool rt_is_exportable(const struct rtentry *rt, struct ucred *cr)
{
    return (true);
}

bool rt_is_host(const struct rtentry *rt);
bool rt_is_host(const struct rtentry *rt)
{
    return (false);
}

struct rtbridge *rtsock_callback_p = NULL;

int sendfile_wait_generic(struct sendfile_sync *sfs, int *err);
int sendfile_wait_generic(struct sendfile_sync *sfs, int *err)
{
    return (0);
}

int tcp_do_ecn = 2;

void tcp_ecn_input_parallel_syn(struct tcpcb *tp, uint16_t thflags, int iptos);
void tcp_ecn_input_parallel_syn(struct tcpcb *tp, uint16_t thflags, int iptos)
{
    
}

int tcp_ecn_input_segment(struct tcpcb *tp, uint16_t thflags, int tlen, int pkts_acked, int iptos);
int tcp_ecn_input_segment(struct tcpcb *tp, uint16_t thflags, int tlen, int pkts_acked, int iptos)
{
    return (0);
}

void tcp_ecn_input_syn_sent(struct tcpcb *tp, uint16_t thflags, int iptos);
void tcp_ecn_input_syn_sent(struct tcpcb *tp, uint16_t thflags, int iptos)
{
    
}

int tcp_ecn_maxretries = 1;

int tcp_ecn_output_established(struct tcpcb *tp, uint16_t *thflags, int len, bool rxmit);
int tcp_ecn_output_established(struct tcpcb *tp, uint16_t *thflags, int len, bool rxmit)
{
    return (0);
}

uint16_t tcp_ecn_output_syn_sent(struct tcpcb *tp);
uint16_t tcp_ecn_output_syn_sent(struct tcpcb *tp)
{
    return (0);
}

void tcp_ecn_syncache_add(struct syncache *sc, int iptos, uint16_t thflags);
void tcp_ecn_syncache_add(struct syncache *sc, int iptos, uint16_t thflags)
{
    
}

uint16_t tcp_ecn_syncache_respond(uint16_t thflags, struct syncache *sc);
uint16_t tcp_ecn_syncache_respond(uint16_t thflags, struct syncache *sc)
{
    return (thflags);
}

void tcp_ecn_syncache_socket(struct tcpcb *tp, struct syncache *sc);
void tcp_ecn_syncache_socket(struct tcpcb *tp, struct syncache *sc)
{
    
}

void (*tcp_hpts_softclock)(void) = NULL;

int tcp_lro_hpts_init(void);
int tcp_lro_hpts_init(void)
{
    return (0);
}

void tcp_lro_hpts_uninit(void);
void tcp_lro_hpts_uninit(void)
{
    
}

void timerfd_jumped(void);
void timerfd_jumped(void)
{
    
}

bool tqhash_empty(void *th);
bool tqhash_empty(void *th)
{
    return (true);
}

void *tqhash_find(void *th, uint32_t key);
void *tqhash_find(void *th, uint32_t key)
{
    return (NULL);
}

void *tqhash_init(uint32_t hash_size);
void *tqhash_init(uint32_t hash_size)
{
    return (NULL);
}

int tqhash_insert(void *th, void *p);
int tqhash_insert(void *th, void *p)
{
    return (0);
}

void *tqhash_max(void *th);
void *tqhash_max(void *th)
{
    return (NULL);
}

void *tqhash_min(void *th);
void *tqhash_min(void *th)
{
    return (NULL);
}

void *tqhash_next(void *th, void *p);
void *tqhash_next(void *th, void *p)
{
    return (NULL);
}

void *tqhash_prev(void *th, void *p);
void *tqhash_prev(void *th, void *p)
{
    return (NULL);
}

int tqhash_remove(void *th, void *p, int how);
int tqhash_remove(void *th, void *p, int how)
{
    return (0);
}

void tqhash_trim(void *th, uint32_t newhash);
void tqhash_trim(void *th, uint32_t newhash)
{
    
}

void tqhash_update_end(void *th, void *p, uint32_t end);
void tqhash_update_end(void *th, void *p, uint32_t end)
{
    
}

void trapsignal(struct thread *td, ksiginfo_t *ksi);
void trapsignal(struct thread *td, ksiginfo_t *ksi)
{
    
}

int uiomove_fromphys(vm_page_t ma[], vm_offset_t offset, int n, struct uio *uio);
int uiomove_fromphys(vm_page_t ma[], vm_offset_t offset, int n, struct uio *uio)
{
    return (EFAULT);
}

vm_page_t vm_page_alloc_noobj_domain(int domain, int req);
vm_page_t vm_page_alloc_noobj_domain(int domain, int req)
{
    return (NULL);
}

struct bitset *vm_page_dump = NULL;

void vm_page_free(vm_page_t m);
void vm_page_free(vm_page_t m)
{
    
}

bool vm_page_unwire_noq(vm_page_t m);
bool vm_page_unwire_noq(vm_page_t m)
{
    return (false);
}

struct vmspace *vmspace_acquire_ref(struct proc *p);
struct vmspace *vmspace_acquire_ref(struct proc *p)
{
    return (NULL);
}

void vmspace_switch_aio(struct vmspace *newvm);
void vmspace_switch_aio(struct vmspace *newvm)
{
    
}

void vm_wait_domain(int domain);
void vm_wait_domain(int domain)
{
    
}

void vnet_rtzone_init(void);
void vnet_rtzone_init(void)
{
    
}


/* ===== End of stubs ===== */
