/*-
 * F-Stack M5: 14.0+ kernel symbol stubs for example/ link.
 *
 * These are user-space stubs for kernel symbols introduced in FreeBSD 14.0+
 * (rib new API, netlink/genl, tcp ECN/HPTS, aio, nvlist, m_snd_tag, tqhash,
 *  prison_check_ip*_locked, vm pages, etc.) referenced by libfstack.ro at link
 * time but not exercised by F-Stack default user-space code paths.
 *
 * Strategy: provide minimal-link-only stubs (no-op functions / zero data) so
 * example/ binaries can link. Runtime invocation of any unimplemented stub
 * indicates code path not supported by user-space F-Stack lib.
 *
 * Auto-generated by /tmp/m5_gen_stub.py — do not hand-edit per-symbol bodies;
 * extend STUBS dict and regenerate instead.
 */

#include <sys/cdefs.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/kernel.h>
#include <sys/systm.h>
#include <sys/errno.h>
#include <sys/lock.h>
#include <sys/mutex.h>
#include <sys/proc.h>
#include <sys/socket.h>
#include <sys/file.h>
#include <sys/malloc.h>
#include <sys/uio.h>
#include <sys/jail.h>
#include <netinet/in.h>
#include <vm/vm.h>
#include <vm/vm_param.h>
#include <vm/vm_page.h>
#include <machine/pmap.h>

/*
 * F-Stack DP-RT-2026-06-01: forward declarations for rtbridge no-op stubs.
 * We deliberately avoid including <net/route/route_ctl.h> here because doing
 * so pulls in conflicting prototypes for other rib_* stubs further down in
 * this file. Instead, declare just the minimal types we need to define the
 * rtbridge initializer below.
 */
struct ifnet;
struct rib_cmd_info;
typedef void route_event_f(uint32_t fibnum, const struct rib_cmd_info *rc);
typedef void ifmsg_event_f(struct ifnet *ifp, int if_flags_mask);
struct rtbridge {
    route_event_f *route_f;
    ifmsg_event_f *ifmsg_f;
};

/* Forward decls for opaque kernel types not pulled by includes above. */
struct kaiocb;
typedef int (aio_cancel_fn_t)(struct kaiocb *);
struct buf_ring;
struct nlattr;
struct nl_pstate;
struct nl_writer;
struct nlmsghdr;
struct nlpcb;
struct nlattr_bmask;
struct rib_head;
struct rib_subscription;
struct rtentry;
struct route_nhop_data;
struct nhop_object;
struct rtbridge;
struct tcpcb;
struct syncache;
struct m_snd_tag;
struct if_snd_tag_sw;
union if_snd_tag_alloc_params;
struct sendfile_sync;
struct vmspace;
struct ksiginfo;
typedef struct ksiginfo ksiginfo_t;
struct nvlist;
typedef struct nvlist nvlist_t;
struct bitset;
typedef struct ifnet *if_t;

/* ===== Stubs (auto-generated) ===== */

int aio_cancel_cleared(struct kaiocb *job);
int aio_cancel_cleared(struct kaiocb *job)
{
    return (0);
}

void aio_clear_cancel_function(struct kaiocb *job);
void aio_clear_cancel_function(struct kaiocb *job)
{
    
}

void aio_complete(struct kaiocb *job, long status, int error);
void aio_complete(struct kaiocb *job, long status, int error)
{
    
}

int aio_set_cancel_function(struct kaiocb *job, aio_cancel_fn_t *func);
int aio_set_cancel_function(struct kaiocb *job, aio_cancel_fn_t *func)
{
    return (0);
}

void aio_switch_vmspace(struct kaiocb *job);
void aio_switch_vmspace(struct kaiocb *job)
{
    
}

void ast_register(int ast, int t, int f, void (*hdlr)(struct thread *, int));
void ast_register(int ast, int t, int f, void (*hdlr)(struct thread *, int))
{
    
}

/*
 * FSTACK runtime-fix: badfileops is now provided by the real definition in
 * freebsd/kern/kern_descrip.c (moved out of the #ifndef FSTACK guard so its
 * 11 badfo_* placeholder ops are linked in).  An all-zero stub here would
 * leave fp->f_ops with a NULL fo_close, crashing _fdrop() in error paths
 * such as kern_accept4 -> noconnection -> fdclose.
 */

int boottrace(const char *tdname, const char *eventfmt, ...);
int boottrace(const char *tdname, const char *eventfmt, ...)
{
    return (0);
}

bool boottrace_enabled = false;

struct buf_ring *buf_ring_alloc(int count, struct malloc_type *type, int flags, struct mtx *lock);
struct buf_ring *buf_ring_alloc(int count, struct malloc_type *type, int flags, struct mtx *lock)
{
    return (NULL);
}

void buf_ring_free(struct buf_ring *br, struct malloc_type *type);
void buf_ring_free(struct buf_ring *br, struct malloc_type *type)
{
    
}

vm_paddr_t dump_avail[16] = {0};

void fdescfree_adapt_use(struct proc *p);
void fdescfree_adapt_use(struct proc *p)
{
    
}

void freeuio(struct uio *uio);
void freeuio(struct uio *uio)
{
    if (uio) free(uio, M_IOV);
}

bool genl_register_cmds(uint16_t family, const void *cmds, int count);
bool genl_register_cmds(uint16_t family, const void *cmds, int count)
{
    return (false);
}

uint16_t genl_register_family(const char *family_name, size_t hdrsize, int family_version, int max_attr_idx);
uint16_t genl_register_family(const char *family_name, size_t hdrsize, int family_version, int max_attr_idx)
{
    return (0);
}

void genl_unregister_family(uint16_t family);
void genl_unregister_family(uint16_t family)
{
    
}

void _gone_in(int major, const char *msg, ...);
void _gone_in(int major, const char *msg, ...)
{
    
}

volatile uint32_t hpts_that_need_softclock = 0;

int inotify_create_file(struct thread *td, struct file *fp, int flags, int *fflagsp);
int inotify_create_file(struct thread *td, struct file *fp, int flags, int *fflagsp)
{
    return (ENOSYS);
}

int invfo_chmod(struct file *fp, mode_t mode, struct ucred *active_cred, struct thread *td);
int invfo_chmod(struct file *fp, mode_t mode, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

int invfo_chown(struct file *fp, uid_t uid, gid_t gid, struct ucred *active_cred, struct thread *td);
int invfo_chown(struct file *fp, uid_t uid, gid_t gid, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

int invfo_rdwr(struct file *fp, struct uio *uio, struct ucred *active_cred, int flags, struct thread *td);
int invfo_rdwr(struct file *fp, struct uio *uio, struct ucred *active_cred, int flags, struct thread *td)
{
    return (EOPNOTSUPP);
}

int invfo_sendfile(struct file *fp, int sockfd, struct uio *hdr_uio, struct uio *trl_uio, off_t offset, size_t nbytes, off_t *sent, int flags, struct thread *td);
int invfo_sendfile(struct file *fp, int sockfd, struct uio *hdr_uio, struct uio *trl_uio, off_t offset, size_t nbytes, off_t *sent, int flags, struct thread *td)
{
    return (EOPNOTSUPP);
}

int invfo_truncate(struct file *fp, off_t length, struct ucred *active_cred, struct thread *td);
int invfo_truncate(struct file *fp, off_t length, struct ucred *active_cred, struct thread *td)
{
    return (EINVAL);
}

bool is_random_seeded(void);
bool is_random_seeded(void)
{
    return (true);
}

void kern_psignal(struct proc *p, int sig);
void kern_psignal(struct proc *p, int sig)
{
    
}

int kproc_create(void (*fn)(void *), void *arg, struct proc **pp, int flags, int pages, const char *fmt, ...);
int kproc_create(void (*fn)(void *), void *arg, struct proc **pp, int flags, int pages, const char *fmt, ...)
{
    return (0);
}

void ktrexterr(struct thread *td);
void ktrexterr(struct thread *td)
{
    
}

struct kva_layout_s kva_layout = {0};

MALLOC_DEFINE(M_NVLIST, "nvlist", "kernel nvlist");

void m_rcvif_restore(struct mbuf *m, if_t ifp, void *cookie);
void m_rcvif_restore(struct mbuf *m, if_t ifp, void *cookie)
{
    
}

void *m_rcvif_serialize(struct mbuf *m);
void *m_rcvif_serialize(struct mbuf *m)
{
    return (NULL);
}

int m_snd_tag_alloc(if_t ifp, union if_snd_tag_alloc_params *params, struct m_snd_tag **mstp);
int m_snd_tag_alloc(if_t ifp, union if_snd_tag_alloc_params *params, struct m_snd_tag **mstp)
{
    return (EOPNOTSUPP);
}

void m_snd_tag_destroy(struct m_snd_tag *mst);
void m_snd_tag_destroy(struct m_snd_tag *mst)
{
    
}

void m_snd_tag_init(struct m_snd_tag *mst, if_t ifp, const struct if_snd_tag_sw *sw);
void m_snd_tag_init(struct m_snd_tag *mst, if_t ifp, const struct if_snd_tag_sw *sw)
{
    
}

void mtx_wait_unlocked(struct mtx *m);
void mtx_wait_unlocked(struct mtx *m)
{
    
}

/*
 * F-Stack DP-RT-2026-06-01: rtbridge no-op stubs.
 *
 * Background: 14.0+ refactored rt_ifmsg() / rt_routemsg() to dispatch via
 * rtsock_callback_p->ifmsg_f() and netlink_callback_p->ifmsg_f() (see
 * 15.0 net/route.c:rt_ifmsg). The original M5 stubs set both pointers to
 * NULL, which causes a SIGSEGV in ifioctl() when configuring an IP via
 * the example startup path.
 *
 * F-Stack does not implement kernel routing-socket or netlink subsystems
 * in user space, but we must not crash. Provide a static rtbridge whose
 * function pointers are no-op shims; rt_ifmsg() / rt_routemsg() callers
 * will then dispatch into harmless no-ops instead of dereferencing NULL.
 */
static void
ff_stub_rt_ifmsg_noop(struct ifnet *ifp __unused, int if_flags_mask __unused)
{
}

static void
ff_stub_rt_routemsg_noop(uint32_t fibnum __unused,
    const struct rib_cmd_info *rc __unused)
{
}

static struct rtbridge ff_stub_rtbridge_noop = {
    .route_f = ff_stub_rt_routemsg_noop,
    .ifmsg_f = ff_stub_rt_ifmsg_noop,
};

struct rtbridge *netlink_callback_p = &ff_stub_rtbridge_noop;

bool nlattr_add(struct nl_writer *nw, uint16_t attr_type, uint16_t attr_len, const void *data);
bool nlattr_add(struct nl_writer *nw, uint16_t attr_type, uint16_t attr_len, const void *data)
{
    return (false);
}

int nlattr_get_in6_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_in6_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_in_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_in_addr(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_nla(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_nla(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_string(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_string(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint16(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint16(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint32(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint32(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_get_uint8(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target);
int nlattr_get_uint8(struct nlattr *nla, struct nl_pstate *npt, const void *arg, void *target)
{
    return (EINVAL);
}

int nlattr_save_offset(struct nl_writer *nw);
int nlattr_save_offset(struct nl_writer *nw)
{
    return (0);
}

int nl_modify_ifp_generic(if_t ifp, struct nlattr_bmask *bm, struct nl_pstate *npt);
int nl_modify_ifp_generic(if_t ifp, struct nlattr_bmask *bm, struct nl_pstate *npt)
{
    return (EOPNOTSUPP);
}

void nlmsg_abort(struct nl_writer *nw);
void nlmsg_abort(struct nl_writer *nw)
{
    
}

bool nlmsg_add(struct nl_writer *nw, uint32_t portid, uint32_t seq, uint16_t type, uint16_t flags, uint32_t len);
bool nlmsg_add(struct nl_writer *nw, uint32_t portid, uint32_t seq, uint16_t type, uint16_t flags, uint32_t len)
{
    return (false);
}

bool nlmsg_end(struct nl_writer *nw);
bool nlmsg_end(struct nl_writer *nw)
{
    return (false);
}

bool nlmsg_end_dump(struct nl_writer *nw, int error, struct nlmsghdr *hdr);
bool nlmsg_end_dump(struct nl_writer *nw, int error, struct nlmsghdr *hdr)
{
    return (false);
}

void nlmsg_report_err_msg(struct nl_pstate *npt, const char *fmt, ...);
void nlmsg_report_err_msg(struct nl_pstate *npt, const char *fmt, ...)
{
    
}

void *nlmsg_reserve_data_raw(struct nl_writer *nw, size_t sz);
void *nlmsg_reserve_data_raw(struct nl_writer *nw, size_t sz)
{
    return (NULL);
}

int nl_parse_attrs_raw(struct nlattr *nla_head, int len, const void *parser, struct nl_pstate *npt, void *target);
int nl_parse_attrs_raw(struct nlattr *nla_head, int len, const void *parser, struct nl_pstate *npt, void *target)
{
    return (EINVAL);
}

struct ucred *nlp_get_cred(struct nlpcb *nlp);
struct ucred *nlp_get_cred(struct nlpcb *nlp)
{
    return (NULL);
}

void nvlist_add_bool(nvlist_t *nvl, const char *name, bool value);
void nvlist_add_bool(nvlist_t *nvl, const char *name, bool value)
{
    
}

nvlist_t *nvlist_create(int flags);
nvlist_t *nvlist_create(int flags)
{
    return (NULL);
}

void nvlist_destroy(nvlist_t *nvl);
void nvlist_destroy(nvlist_t *nvl)
{
    
}

int nvlist_error(const nvlist_t *nvl);
int nvlist_error(const nvlist_t *nvl)
{
    return (0);
}

bool nvlist_exists_bool(const nvlist_t *nvl, const char *name);
bool nvlist_exists_bool(const nvlist_t *nvl, const char *name)
{
    return (false);
}

bool nvlist_get_bool(const nvlist_t *nvl, const char *name);
bool nvlist_get_bool(const nvlist_t *nvl, const char *name)
{
    return (false);
}

void *nvlist_pack(const nvlist_t *nvl, size_t *sizep);
void *nvlist_pack(const nvlist_t *nvl, size_t *sizep)
{
    return (NULL);
}

nvlist_t *nvlist_unpack(const void *buf, size_t size, int flags);
nvlist_t *nvlist_unpack(const void *buf, size_t size, int flags)
{
    return (NULL);
}

const struct fileops path_fileops = {0};

vm_page_t PHYS_TO_VM_PAGE(vm_paddr_t pa);
vm_page_t PHYS_TO_VM_PAGE(vm_paddr_t pa)
{
    return (NULL);
}

int prison_check_ip4_locked(const struct prison *pr, const struct in_addr *ia);
int prison_check_ip4_locked(const struct prison *pr, const struct in_addr *ia)
{
    return (0);
}

int prison_check_ip6_locked(const struct prison *pr, const struct in6_addr *ia6);
int prison_check_ip6_locked(const struct prison *pr, const struct in6_addr *ia6)
{
    return (0);
}

bool prison_isalive(const struct prison *pr);
bool prison_isalive(const struct prison *pr)
{
    return (true);
}

void rack_update_pcm_ack(void *rack, int was_pcm, uint32_t ack, uint32_t to);
void rack_update_pcm_ack(void *rack, int was_pcm, uint32_t ack, uint32_t to)
{
    
}

void rib_destroy_subscriptions(struct rib_head *rnh);
void rib_destroy_subscriptions(struct rib_head *rnh)
{
    
}

void rib_init_subscriptions(struct rib_head *rnh);
void rib_init_subscriptions(struct rib_head *rnh)
{
    
}

void rib_notify(struct rib_head *rnh, int type, void *data);
void rib_notify(struct rib_head *rnh, int type, void *data)
{
    
}

struct rib_subscription *rib_subscribe_internal(struct rib_head *rnh, void (*cb)(struct rib_head *, void *, void *), void *arg, int type, bool waitok);
struct rib_subscription *rib_subscribe_internal(struct rib_head *rnh, void (*cb)(struct rib_head *, void *, void *), void *arg, int type, bool waitok)
{
    return (NULL);
}

/*
 * F-Stack DP-RT-FIX-1 (2026-06-01 20:52): rt_*() stubs removed.
 *
 * These 11 rt_* functions were originally stubbed here in M5 because the
 * link-time symbol-discovery generator did not realize freebsd/net/route/
 * route_rtentry.c provides the real implementations. Worse, rt_alloc()'s
 * stub had the wrong signature (3rd arg `struct route_nhop_data *` instead
 * of the real `struct sockaddr *netmask`) and unconditionally returned
 * NULL, which caused rib_add_route() -> add_route_byinfo() to bail out
 * with ENOBUFS (errno 55) — making ff_veth_setaddr() and
 * ifa_maintain_loopback_route() always fail, so f-stack-0 never got
 * `inet 9.134.214.176`.
 *
 * Real implementations now come from route_rtentry.o (added to
 * VM/NET_SRCS in lib/Makefile in the same change). The functions
 * resolved by route_rtentry.o are:
 *   rt_alloc, rt_free, rt_free_immediate, rt_is_host, rt_get_family,
 *   rt_get_raw_nhop, rt_get_rnd, rt_is_exportable,
 *   rt_get_inet_prefix_plen,  rt_get_inet_prefix_pmask,
 *   rt_get_inet6_prefix_plen, rt_get_inet6_prefix_pmask,
 *   vnet_rtzone_init, vnet_rtzone_destroy.
 *
 * Keeping any of the old stubs here would create a multiple-definition
 * link error or, worse, win over the real implementation depending on
 * archive order. Hence: removed wholesale.
 */

/* See ff_stub_rtbridge_noop above for context. */
struct rtbridge *rtsock_callback_p = &ff_stub_rtbridge_noop;

int sendfile_wait_generic(struct sendfile_sync *sfs, int *err);
int sendfile_wait_generic(struct sendfile_sync *sfs, int *err)
{
    return (0);
}

/*
 * ECN stubs (tcp_do_ecn/tcp_ecn_maxretries + 8 tcp_ecn_* no-ops) removed:
 * under VIMAGE V_tcp_do_ecn needs the real VNET_DEFINE segment symbols,
 * provided by the now-compiled freebsd/netinet/tcp_ecn.c.
 */

void (*tcp_hpts_softclock)(void) = NULL;

int tcp_lro_hpts_init(void);
int tcp_lro_hpts_init(void)
{
    return (0);
}

void tcp_lro_hpts_uninit(void);
void tcp_lro_hpts_uninit(void)
{
    
}

void timerfd_jumped(void);
void timerfd_jumped(void)
{
    
}

bool tqhash_empty(void *th);
bool tqhash_empty(void *th)
{
    return (true);
}

void *tqhash_find(void *th, uint32_t key);
void *tqhash_find(void *th, uint32_t key)
{
    return (NULL);
}

void *tqhash_init(uint32_t hash_size);
void *tqhash_init(uint32_t hash_size)
{
    return (NULL);
}

int tqhash_insert(void *th, void *p);
int tqhash_insert(void *th, void *p)
{
    return (0);
}

void *tqhash_max(void *th);
void *tqhash_max(void *th)
{
    return (NULL);
}

void *tqhash_min(void *th);
void *tqhash_min(void *th)
{
    return (NULL);
}

void *tqhash_next(void *th, void *p);
void *tqhash_next(void *th, void *p)
{
    return (NULL);
}

void *tqhash_prev(void *th, void *p);
void *tqhash_prev(void *th, void *p)
{
    return (NULL);
}

int tqhash_remove(void *th, void *p, int how);
int tqhash_remove(void *th, void *p, int how)
{
    return (0);
}

void tqhash_trim(void *th, uint32_t newhash);
void tqhash_trim(void *th, uint32_t newhash)
{
    
}

void tqhash_update_end(void *th, void *p, uint32_t end);
void tqhash_update_end(void *th, void *p, uint32_t end)
{
    
}

void trapsignal(struct thread *td, ksiginfo_t *ksi);
void trapsignal(struct thread *td, ksiginfo_t *ksi)
{
    
}

int uiomove_fromphys(vm_page_t ma[], vm_offset_t offset, int n, struct uio *uio);
int uiomove_fromphys(vm_page_t ma[], vm_offset_t offset, int n, struct uio *uio)
{
    return (EFAULT);
}

/*
 * F-Stack runtime-fix DP-RT-2026-06-01: vm_page_alloc_noobj_domain panic stub.
 *
 * Background: M5 introduced a "return NULL" stub here so example/ could link.
 * Runtime debug found this causes an infinite spin loop in uma_startup1 ->
 * keg_fetch_slab when UMA_USE_DMAP picks uma_small_alloc as the allocator
 * (root cause: amd64/arm64 vmparam.h forgot the #ifndef FSTACK guard around
 * UMA_USE_DMAP after the 14.0+ rename from UMA_MD_SMALL_ALLOC).
 *
 * The vmparam.h fix already routes uma to page_alloc -> kmem_malloc, so this
 * stub should NEVER be called at runtime in normal F-Stack flows. Make any
 * stray call fail loudly via panic() so a future regression (e.g. another
 * subsystem accidentally taking the vm_page path) is exposed immediately
 * instead of silently spinning the CPU.
 */
vm_page_t vm_page_alloc_noobj_domain(int domain, int req);
vm_page_t vm_page_alloc_noobj_domain(int domain, int req)
{
    panic("F-Stack: vm_page_alloc_noobj_domain stub called (domain=%d req=%#x); "
          "this indicates UMA picked uma_small_alloc — check UMA_USE_DMAP guard "
          "in freebsd/{amd64,arm64}/include/vmparam.h",
          domain, req);
    return (NULL); /* unreachable, keeps compiler happy */
}

vm_page_t vm_page_alloc_noobj(int req);
vm_page_t vm_page_alloc_noobj(int req)
{
    panic("F-Stack: vm_page_alloc_noobj stub called (req=%#x); "
          "this indicates pcpu_page_alloc / similar vm-page path was taken — "
          "check UMA_USE_DMAP guard in freebsd/{amd64,arm64}/include/vmparam.h",
          req);
    return (NULL); /* unreachable */
}

struct bitset *vm_page_dump = NULL;

void vm_page_free(vm_page_t m);
void vm_page_free(vm_page_t m)
{
    
}

bool vm_page_unwire_noq(vm_page_t m);
bool vm_page_unwire_noq(vm_page_t m)
{
    return (false);
}

struct vmspace *vmspace_acquire_ref(struct proc *p);
struct vmspace *vmspace_acquire_ref(struct proc *p)
{
    return (NULL);
}

void vmspace_switch_aio(struct vmspace *newvm);
void vmspace_switch_aio(struct vmspace *newvm)
{
    
}

void vm_wait_domain(int domain);
void vm_wait_domain(int domain)
{
    
}

/*
 * vnet_rtzone_init stub removed: real implementation now provided by
 * route_rtentry.o (see DP-RT-FIX-1 comment block above for full
 * background).
 */


/* ============================================================
 * M6 (FF_NETGRAPH + FF_IPFW combo) added stubs — 2026-06-08
 *
 * 4 symbols surfaced by example/helloworld link after enabling
 * FF_IPFW=1 in lib/Makefile. Signatures matched against
 * freebsd-src-releng-15.0/sys/netpfil/ipfw/ip_fw_private.h
 * (ipfw_bpf_*) and sys/netinet/sctp_crc32.h (sctp_calculate_cksum).
 *
 * Background:
 *   - ip_fw_bpf.c is intentionally NOT in NETIPFW_SRCS (M6 spec
 *     §1.2 / §2.4); ipfw rule logging via BPF is not exercised in
 *     user-space F-Stack.
 *   - sctp_calculate_cksum is referenced by ip_fw2.c:615 and
 *     uma_core.c (transitive) but SCTP is not ported in F-Stack.
 *
 * All four are link-only stubs; runtime invocation indicates a
 * code path not supported in user-space and returns harmlessly
 * (BPF taps no-op, SCTP cksum returns 0 — same as upstream when
 * checksum offload is delegated to NIC).
 * ============================================================ */

/* No <sys/mbuf.h> — would conflict with the file's local
 * m_rcvif_restore stub (different signature, FreeBSD 13/15 ABI).
 * struct mbuf is only referenced by pointer here so a fwd decl
 * suffices.  u_char / u_int / int32_t / uint32_t are already in
 * scope via <sys/types.h> included near the top of the file.
 */
struct mbuf;

void ipfw_bpf_init(int onoff);
void ipfw_bpf_init(int onoff)
{
    (void)onoff;
}

void ipfw_bpf_uninit(int onoff);
void ipfw_bpf_uninit(int onoff)
{
    (void)onoff;
}

void ipfw_bpf_tap(u_char *pkt, u_int len);
void ipfw_bpf_tap(u_char *pkt, u_int len)
{
    (void)pkt;
    (void)len;
}

uint32_t sctp_calculate_cksum(struct mbuf *m, int32_t offset);
uint32_t sctp_calculate_cksum(struct mbuf *m, int32_t offset)
{
    (void)m;
    (void)offset;
    return (0);
}

/* M6 follow-up — second link pass surfaced 3 more symbols
 * (prng32_bounded from ng_pipe.c; ipfw_bpf_mtap / ipfw_bpf_mtap2
 * from ip_fw_log.c). Signatures from sys/prng.h:13 and
 * sys/netpfil/ipfw/ip_fw_private.h:165-166. */

__uint32_t prng32_bounded(__uint32_t bound);
__uint32_t prng32_bounded(__uint32_t bound)
{
    return (bound > 0 ? (__uint32_t)0 : (__uint32_t)0);
}

void ipfw_bpf_mtap(struct mbuf *m);
void ipfw_bpf_mtap(struct mbuf *m)
{
    (void)m;
}

void ipfw_bpf_mtap2(void *arg, u_int len, struct mbuf *m);
void ipfw_bpf_mtap2(void *arg, u_int len, struct mbuf *m)
{
    (void)arg;
    (void)len;
    (void)m;
}

/*
 * M13 (FF_LOOPBACK_SUPPORT) link-only stub. Declared in
 * lib/ff_host_interface.h:92 and called from ff_dpdk_if.c:2445
 * inside the loopback poll loop, but never had a real
 * implementation in the F-Stack tree (M0~M12 build never had
 * FF_LOOPBACK_SUPPORT enabled so the symbol was a dead reference).
 *
 * The function is intended to drive a software-interrupt-style
 * network packet executor; in user-space F-Stack the equivalent
 * work is done inline by ff_dpdk_if main loop, so a no-op stub is
 * a safe fallback. Smoke testing only — full loopback semantics
 * may require revisit if a runtime path actually relies on this.
 */
void ff_swi_net_excute(void);
void ff_swi_net_excute(void)
{
}


/* ===== End of stubs ===== */
