# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017 NXP

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_EXEC_ENV_FREEBSD) += contigmem
DIRS-$(CONFIG_RTE_EXEC_ENV_FREEBSD) += nic_uio

include $(RTE_SDK)/mk/rte.subdir.mk
