# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
# Copyright 2017 NXP

include $(RTE_SDK)/mk/rte.vars.mk

DIRS-$(CONFIG_RTE_EXEC_ENV_LINUX) += linux
DIRS-$(CONFIG_RTE_EXEC_ENV_FREEBSD) += freebsd

include $(RTE_SDK)/mk/rte.subdir.mk
