#   SPDX-License-Identifier: BSD-3-Clause
#   Copyright(c) 2017 Intel Corporation.

# makefile for building kernel modules using meson
# takes parameters from the environment

# source file is passed via KMOD_SRC as full path, we only use final
# component of it, as VPATH is used to find actual file, so as to
# have the .o files placed in the build, not source directory
VPATH = ${KMOD_SRC:H}
SRCS = ${KMOD_SRC:T} device_if.h bus_if.h pci_if.h
CFLAGS += $(KMOD_CFLAGS)

.include <bsd.kmod.mk>
