# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2013 Neil Horman <nhorman@tuxdriver.com>
# All rights reserved.

include $(RTE_SDK)/mk/rte.vars.mk


LIBABIVER := 1

# install includes
SYMLINK-y-include := rte_compat.h

include $(RTE_SDK)/mk/rte.install.mk
